### ISSUE TITLE
Update key software versions

### ISSUE THREAD

**Issue by kocio-pl** [pitrho/docker-postgres#1]
Do you plan to update the image to Ubuntu 16.04 ([phusion/baseimage 0.9.19](https://github.com/phusion/baseimage-docker/blob/master/Changelog.md#0919-release-date-2016-07-08)) and Postgres version to 9.5?

**Comment by thegalexc** [comment]
This allows you to specify the Postgres version when building (e.g. ./build.sh -v 9.5). We have built a new image and pushed to DockerHub under pitrho/postgres:9.5. We also tagged our 9.4 image as pitrho/postgres:9.4 (which continues to be the :latest tag).

Is there a particular reason you'd like to see 16.04 as the base image?

**Comment by kocio-pl** [comment]
I was interested in [making installation image for OpenStreetMap default style](https://github.com/gravitystorm/openstreetmap-carto/issues/657) and we use 16.04 lately. However I forgot we also need PostGIS, but I guess this image doesn't include it.

**Comment by thegalexc** [comment]
Sounds good. You can use the pitrho/postgres:9.5 image for your database regardless of what is used in your other images. The key feature of this repo is the backup-to-S3 functionality.
